name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # This job will run linting, typechecking and tests on your codebase
  testCodebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.14.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2

      # Install packages
      - run: npm i

      # Generate prisma client & push to db
      - run: echo "DATABASE_URL=file:./db.sqlite" > .env
      - run: npx prisma db push
      - run: npx prisma generate

      # Run linting and typechecking
      - run: npm run lint
      - run: npm run typecheck

      # Run tests
      - run: npm run test
